[images.hello]
tag = ["test-hello:v1", "localhost:5000/test-hello:v1"]
dockerfile = "./hello/Dockerfile"

[images.hello2]
tag = ["test-hello:v2", "localhost:5000/test-hello:v2"]
dockerfile = "./hello2/Dockerfile"

[images.hello3]
tag = ["test-hello:v3", "localhost:5000/test-hello:v3"]
dockerfile = "./hello3/Dockerfile"

[images.hello4]
tag = ["test-hello:v4", "localhost:5000/test-hello:v4"]
dockerfile = "./hello4/Dockerfile"

